# Generated by Django 3.1.5 on 2021-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
